commonLabels:
  prometheus: default

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
  serviceMonitorSelector: []
  ## Example which selects ServiceMonitors with label "prometheus" set to "somelabel"
  # serviceMonitorSelector:
    # matchLabels:
    #   prometheus: default

grafana:
    additionalDataSources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        jsonData:
          maxLines: 1000
